# Generated by Django 4.2.15 on 2024-08-12 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weekapp', '0002_author_city_alter_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(18)]),
        ),
    ]
